# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28a3e0bbd8f9492e922e808e4073856d251e704de40f3d878edebea3492ec90a8c82b7270a516a5924cb2c62b241d7bfa55292d73235fc95f724e772846b87fa

test:
  secret_key_base: 10ee8f495e524b53548128976edecfb6a414dc489b4fc50dfa19c9c63109ea43b7d58158e0499f37b0dc7a167231427a1cb71cb792c832f51edbcc00eeb35e8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
